// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsweqjftpgslnmsabbqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzd2VxamZ0cGdzbG5tc2FiYnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTAxNTcsImV4cCI6MjA2MDU2NjE1N30.H0xpHAYIKjPfYoRFYXQVJn-7YNoaBU9nG0T_QNrdqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);